### ISSUE TITLE
Need a full form to be filled out

### ISSUE THREAD

**Issue by brossetti1** [mjohnson518/ChainShot_Final_Project#15]
@mjohnson518 

1) so we are going to need you to open up a form and fill out an entire form with sensisible answers. Once we have that data in there

2) also, if you could try to pick out some of these atttributes that make the most sense to make the table out of - you can use the `emmissionsData.js` to throw the column names that make the most sense as display fields in the table:

we can also add custom logic to display fields that are a combination of the data or not in the data at all if that makes sense.

one field in the image is `status` - guessing we could do something like status [`minted`, `not minted`] or something anyways, just throwing ideas out there. 

table for reference
![Screen Shot 2021-09-04 at 9 39 30 PM](https://user-images.githubusercontent.com/5998100/132120624-29f7d4a5-3caa-4f93-9a52-5e16099bfaf7.png)

**Comment by mjohnson518** [comment]
I really like the `Status` tag. `Active`, `Reviewing`, `Declined`, `Minted` all sound like good status codes. Do you have any other in mind? 

Is there anyway we could have collapsable table attributes? 

Suggested table attributes:

1. general:
> - companyName
> - productName

2.  boundary
> - systemBoundary
> - timePeriod

3. dataCollection
> - primaryDataShare
> - dataCollectionMethod

4. allocation
> - standards

5. inventoryResults
> - productPCF

**Comment by brossetti1** [comment]
@mjohnson518 so this is good - is there a simplified version of those table attribuets? its going to overflow off the screen otherwise - any of those that are less necessary for the display part of the app?



![Screen Shot 2021-09-05 at 1 41 23 PM](https://user-images.githubusercontent.com/5998100/132139471-a61db00d-1809-4e29-8bc0-afcb81e14a81.png)

**Comment by mjohnson518** [comment]
Slimmed table attributes:

1. general:
> - companyName
> - productName

2. boundary:
> - timePeriod

3. dataCollection:
> - primaryDataShare

4. inventoryResults:
> - productPCF
