### ISSUE TITLE
recreate Logo to what you want

### ISSUE THREAD

**Issue by brossetti1** [mjohnson518/ChainShot_Final_Project#23]
@mjohnson518 so i know you wanted the logo to say something else - you can generate them here:

https://hatchful.shopify.com/

if you could generate one, mess around with the settings and find one you like, then it will be downloadable and be sent to the email address you sigend up wtih

no rush, just when you have time.

**Comment by mjohnson518** [comment]
![Snip20210912_47](https://user-images.githubusercontent.com/44822571/133004611-327eb6bf-c3e7-4e73-affb-af85db48efed.png)

**Comment by mjohnson518** [comment]
![logo_light_transparent](https://user-images.githubusercontent.com/44822571/133005021-fa63da44-0985-4e64-aa4c-44b23acf5717.png)

**Comment by mjohnson518** [comment]
![logo_dark_transparent](https://user-images.githubusercontent.com/44822571/133005031-c3ad2714-a674-48dd-98a4-5dd56e633a31.png)

**Comment by mjohnson518** [comment]
[c12-logo-light.zip](https://github.com/mjohnson518/ChainShot_Final_Project/files/7150415/c12-logo-light.zip)
[c12-logo-dark.zip](https://github.com/mjohnson518/ChainShot_Final_Project/files/7150417/c12-logo-dark.zip)
