### ISSUE TITLE
Typeform Questionnaire

### ISSUE THREAD

**Issue by mjohnson518** [mjohnson518/ChainShot_Final_Project#8]
@mjohnson518 to make questionnaire on Typeform

**Comment by brossetti1** [comment]
[EmissionsData.js](https://github.com/mjohnson518/ChainShot_Final_Project/blob/main/frontend/src/components/EmmissionsData.js) contains the keys for the form layout - we need to add these keys to the `block reference` names when we finish the form.

<img width="378" alt="Screen Shot 2021-09-03 at 3 07 09 PM" src="https://user-images.githubusercontent.com/5998100/132065367-4227cc40-5d2f-4fa9-9115-b8f6848b41b5.png">


# references to the block references

 we need to match `Emissions.js` keys with this form here @mjohnson518 
<img width="858" alt="Screen Shot 2021-09-03 at 3 10 00 PM" src="https://user-images.githubusercontent.com/5998100/132065680-74fb944a-5ab8-4e9c-8849-3ad55aea0435.png">

**Comment by mjohnson518** [comment]
@brossetti1 can you invite me to the typeform account?

**Comment by mjohnson518** [comment]
Done

**Comment by brossetti1** [comment]
closing this one
